name: Build React-App and deploy to Surge

on: [push]
    

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16.2.0'

    - name: Install dependencies
      run: |
        npm install
        npm install surge
    - name: Build
      run: |
        npm run build
    - name: Deploy
      run: |
        cd build 